services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo
    networks:
      - url-shortener-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge

volumes:
  mongodb_data: